"""empty message

Revision ID: 2773209756a6
Revises: b064c3bd6184
Create Date: 2021-09-04 12:42:31.472408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2773209756a6'
down_revision = 'b064c3bd6184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'leaser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('leaser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
