"""empty message

Revision ID: 3d2fd479c548
Revises: 535eb55aadab
Create Date: 2021-07-31 00:06:40.952661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2fd479c548'
down_revision = '535eb55aadab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('startTime', sa.String(), nullable=False))
    op.add_column('reservations', sa.Column('endTime', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'endTime')
    op.drop_column('reservations', 'startTime')
    # ### end Alembic commands ###
