"""empty message

Revision ID: 535eb55aadab
Revises: 7c45c878d078
Create Date: 2021-07-31 00:05:55.145839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '535eb55aadab'
down_revision = '7c45c878d078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'endTime')
    op.drop_column('reservations', 'startTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('startTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('reservations', sa.Column('endTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
