"""empty message

Revision ID: 7c45c878d078
Revises: f0aafd6694cc
Create Date: 2021-07-29 12:33:40.019874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c45c878d078'
down_revision = 'f0aafd6694cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('imageUrl', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'imageUrl')
    # ### end Alembic commands ###
