"""empty message

Revision ID: 80f4f84c64ab
Revises: e4c884392f78
Create Date: 2021-08-04 20:04:01.280146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f4f84c64ab'
down_revision = 'e4c884392f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('imageUrl', sa.String(length=3000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'imageUrl')
    # ### end Alembic commands ###
