"""empty message

Revision ID: a781086cdffe
Revises: a86bf9c46ac0
Create Date: 2021-07-31 16:33:49.809812

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")



# revision identifiers, used by Alembic.
revision = 'a781086cdffe'
down_revision = 'a86bf9c46ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'stars')
    if environment == "production":
        op.execute(f"ALTER TABLE <table_name> SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('stars', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
