"""empty message

Revision ID: f918909584ed
Revises: 80f4f84c64ab
Create Date: 2021-08-04 22:36:49.847226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f918909584ed'
down_revision = '80f4f84c64ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('imageUrl', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'imageUrl')
    # ### end Alembic commands ###
